# Generated by Django 3.0.7 on 2020-06-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, null=True)),
                ('cls_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectures_analyzer.Cls'),
        ),
    ]
